version: "3.9"  # optional since v1.27.0
services:
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    networks:
      - leibniz-local

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    networks:
      - leibniz-local

  argument-access:
    build:
      context: .
      dockerfile: be/Dockerfile
    init: true
    command: sh -c "git config --global --add safe.directory /app && cd ./be/services/argument-access && air"
    env_file:
        - ././be/services/argument-access/.env.prod
    ports:
      - "9002:9002"
      - "8080:8080"
    volumes:
      - ./:/app
      - /root/.cache/go-build
      - go-mod-cache:/go/pkg/mod
    networks:
      - leibniz-local
    depends_on:
      - mongo

  fe:
    build:
      context: .
      dockerfile: fe/Dockerfile
    command: sh -c "cd ./fe && npm run dev -- --host"
    ports:
      - "5173:5173"
    networks:
      - leibniz-local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


volumes:
  go-mod-cache:

networks:
  leibniz-local:
