syntax = "proto3";

import "google/api/annotations.proto";
// import "argumentaccess/v1/argument.proto";

option go_package = "go/argumentmanager/v1;argumentmanager";

package argumentmanager.v1;

service ArgumentManager {
	rpc Check (HealthCheckRequest) returns (HealthCheckResponse);
	rpc Watch (HealthCheckRequest) returns (stream HealthCheckResponse);

	rpc Test (TestRequest) returns (TestResponse) {
		option (google.api.http) = {
			get: "/test"
		  };
	}
}

message HealthCheckRequest {
	string service = 1;
}

message HealthCheckResponse {
	enum ServingStatus {
	  UNKNOWN = 0;
	  SERVING = 1;
	  NOT_SERVING = 2;
	  SERVICE_UNKNOWN = 3;  // Used only by the Watch method.
	}
	ServingStatus status = 1;
}

message TestRequest {
}

message TestResponse {
}
