// @generated by protobuf-ts 2.8.2 with parameter generate_dependencies
// @generated from protobuf file "argumentmanager/v1/server.proto" (package "argumentmanager.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ArgumentManager } from "./server";
import type { TestResponse } from "./server";
import type { TestRequest } from "./server";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { HealthCheckResponse } from "./server";
import type { HealthCheckRequest } from "./server";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service argumentmanager.v1.ArgumentManager
 */
export interface IArgumentManagerClient {
    /**
     * @generated from protobuf rpc: Check(argumentmanager.v1.HealthCheckRequest) returns (argumentmanager.v1.HealthCheckResponse);
     */
    check(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckResponse>;
    /**
     * @generated from protobuf rpc: Watch(argumentmanager.v1.HealthCheckRequest) returns (stream argumentmanager.v1.HealthCheckResponse);
     */
    watch(input: HealthCheckRequest, options?: RpcOptions): ServerStreamingCall<HealthCheckRequest, HealthCheckResponse>;
    /**
     * @generated from protobuf rpc: Test(argumentmanager.v1.TestRequest) returns (argumentmanager.v1.TestResponse);
     */
    test(input: TestRequest, options?: RpcOptions): UnaryCall<TestRequest, TestResponse>;
}
/**
 * @generated from protobuf service argumentmanager.v1.ArgumentManager
 */
export class ArgumentManagerClient implements IArgumentManagerClient, ServiceInfo {
    typeName = ArgumentManager.typeName;
    methods = ArgumentManager.methods;
    options = ArgumentManager.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Check(argumentmanager.v1.HealthCheckRequest) returns (argumentmanager.v1.HealthCheckResponse);
     */
    check(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HealthCheckRequest, HealthCheckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Watch(argumentmanager.v1.HealthCheckRequest) returns (stream argumentmanager.v1.HealthCheckResponse);
     */
    watch(input: HealthCheckRequest, options?: RpcOptions): ServerStreamingCall<HealthCheckRequest, HealthCheckResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<HealthCheckRequest, HealthCheckResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Test(argumentmanager.v1.TestRequest) returns (argumentmanager.v1.TestResponse);
     */
    test(input: TestRequest, options?: RpcOptions): UnaryCall<TestRequest, TestResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<TestRequest, TestResponse>("unary", this._transport, method, opt, input);
    }
}
