apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "argument-access.fullname" . }}
    labels: {{- include "argument-access.labels" . | nindent 4 }}
data:
    {{- toYaml .Values.config | nindent 2 }}