## Prod values for argument-access chart
config:

service:
  type: NodePort
  nodePort: 31242
  port: 80

healthCheckService:
  enabled: true
  port: 8080
  targetPort: 8080
  nodePort: 31243 # must be explicit so we can congifure Google's health check probe. Only has an effect if service.type is 'NodePort'
