// @generated by protobuf-ts 2.8.2 with parameter generate_dependencies
// @generated from protobuf file "argumentaccess/v1/argument.proto" (package "argumentaccess.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../../google/protobuf/timestamp";
/**
 * @generated from protobuf message argumentaccess.v1.Argument
 */
export interface Argument {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string; // @gotags: bson:"_id"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 2;
     */
    createdAt?: Timestamp; // @gotags: bson:"created_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 3;
     */
    updatedAt?: Timestamp; // @gotags: bson:"updated_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp deleted_at = 4;
     */
    deletedAt?: Timestamp; // @gotags: bson:"deleted_at"
    /**
     * @generated from protobuf field: string title = 5;
     */
    title: string; // @gotags: bson:"title"
    /**
     * @generated from protobuf field: repeated argumentaccess.v1.Premise premises = 6;
     */
    premises: Premise[]; // @gotags: bson:"premises"
    /**
     * @generated from protobuf field: repeated argumentaccess.v1.ConditionalStatement conditional_statements = 7;
     */
    conditionalStatements: ConditionalStatement[]; // @gotags: bson:"conditional_statements"
    /**
     * @generated from protobuf field: argumentaccess.v1.Premise conclusion_premise = 8;
     */
    conclusionPremise?: Premise; // @gotags: bson:"conclusion_premise"
}
/**
 * @generated from protobuf message argumentaccess.v1.ConditionalStatement
 */
export interface ConditionalStatement {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string; // @gotags: bson:"_id"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 2;
     */
    createdAt?: Timestamp; // @gotags: bson:"created_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 3;
     */
    updatedAt?: Timestamp; // @gotags: bson:"updated_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp deleted_at = 4;
     */
    deletedAt?: Timestamp; // @gotags: bson:"deleted_at"
    /**
     * @generated from protobuf field: argumentaccess.v1.Premise if_premise = 5;
     */
    ifPremise?: Premise; // @gotags: bson:"if_premise" 
    /**
     * @generated from protobuf field: argumentaccess.v1.Premise then_premise = 6;
     */
    thenPremise?: Premise; // @gotags: bson:"then_premise" 
    /**
     * @generated from protobuf field: argumentaccess.v1.Proposition if_proposition = 7;
     */
    ifProposition?: Proposition; // @gotags: bson:"if_proposition" 
    /**
     * @generated from protobuf field: argumentaccess.v1.Proposition then_proposition = 8;
     */
    thenProposition?: Proposition; // @gotags: bson:"then_proposition" 
}
/**
 * @generated from protobuf message argumentaccess.v1.Proposition
 */
export interface Proposition {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string; // @gotags: bson:"_id"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 2;
     */
    createdAt?: Timestamp; // @gotags: bson:"created_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 3;
     */
    updatedAt?: Timestamp; // @gotags: bson:"updated_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp deleted_at = 4;
     */
    deletedAt?: Timestamp; // @gotags: bson:"deleted_at"
    /**
     * @generated from protobuf field: argumentaccess.v1.PropositionType proposition_type = 9;
     */
    propositionType: PropositionType; // @gotags: bson:"proposition_type" 
    /**
     * @generated from protobuf field: repeated argumentaccess.v1.Premise proposition_sub_premises = 10;
     */
    propositionSubPremises: Premise[]; // @gotags: bson:"proposition_sub_premises" 
    /**
     * @generated from protobuf field: repeated argumentaccess.v1.Proposition proposition_sub_propositions = 11;
     */
    propositionSubPropositions: Proposition[]; // @gotags: bson:"proposition_sub_propositions" 
}
/**
 * @generated from protobuf message argumentaccess.v1.Premise
 */
export interface Premise {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string; // @gotags: bson:"_id"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 2;
     */
    createdAt?: Timestamp; // @gotags: bson:"created_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 3;
     */
    updatedAt?: Timestamp; // @gotags: bson:"updated_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp deleted_at = 4;
     */
    deletedAt?: Timestamp; // @gotags: bson:"deleted_at"
    /**
     * @generated from protobuf field: argumentaccess.v1.Subject subject = 5;
     */
    subject?: Subject; // @gotags: bson:"subject" 
    /**
     * X is Y, subject = X
     *
     * @generated from protobuf field: argumentaccess.v1.SubjectQuantifier subject_quantifier = 6;
     */
    subjectQuantifier: SubjectQuantifier; // @gotags: bson:"subject_quantifier"
    /**
     * all X is Y, subject_quantifier = all
     *
     * @generated from protobuf field: argumentaccess.v1.Predicate predicate = 7;
     */
    predicate?: Predicate; // @gotags: bson:"predicate"
    /**
     * X is Y, predicate = Y, premises should have EITHER a subject and a predicate OR subpremises
     *
     * @generated from protobuf field: argumentaccess.v1.PredicateQualifier predicate_qualifier = 8;
     */
    predicateQualifier: PredicateQualifier; // @gotags: bson:"predicate_qualifier"
}
/**
 * @generated from protobuf message argumentaccess.v1.Subject
 */
export interface Subject {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string; // @gotags: bson:"_id"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 2;
     */
    createdAt?: Timestamp; // @gotags: bson:"created_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 3;
     */
    updatedAt?: Timestamp; // @gotags: bson:"updated_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp deleted_at = 4;
     */
    deletedAt?: Timestamp; // @gotags: bson:"deleted_at"
    /**
     * @generated from protobuf field: string body = 5;
     */
    body: string; // @gotags: bson:"body"
}
/**
 * @generated from protobuf message argumentaccess.v1.Predicate
 */
export interface Predicate {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string; // @gotags: bson:"_id"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 2;
     */
    createdAt?: Timestamp; // @gotags: bson:"created_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 3;
     */
    updatedAt?: Timestamp; // @gotags: bson:"updated_at"
    /**
     * @generated from protobuf field: google.protobuf.Timestamp deleted_at = 4;
     */
    deletedAt?: Timestamp; // @gotags: bson:"deleted_at"
    /**
     * @generated from protobuf field: string body = 5;
     */
    body: string; // @gotags: bson:"body"
}
/**
 * @generated from protobuf enum argumentaccess.v1.PropositionType
 */
export enum PropositionType {
    /**
     * @generated from protobuf enum value: AND = 0;
     */
    AND = 0,
    /**
     * @generated from protobuf enum value: OR = 1;
     */
    OR = 1,
    /**
     * @generated from protobuf enum value: NAND = 2;
     */
    NAND = 2,
    /**
     * @generated from protobuf enum value: NOR = 3;
     */
    NOR = 3,
    /**
     * @generated from protobuf enum value: XOR = 4;
     */
    XOR = 4,
    /**
     * @generated from protobuf enum value: XNOR = 5;
     */
    XNOR = 5
}
/**
 * @generated from protobuf enum argumentaccess.v1.SubjectQuantifier
 */
export enum SubjectQuantifier {
    /**
     * @generated from protobuf enum value: ALL = 0;
     */
    ALL = 0,
    /**
     * @generated from protobuf enum value: SOME = 1;
     */
    SOME = 1,
    /**
     * PARTICULAR = 3; // TODO do later?
     *
     * @generated from protobuf enum value: NONE = 2;
     */
    NONE = 2
}
/**
 * @generated from protobuf enum argumentaccess.v1.PredicateQualifier
 */
export enum PredicateQualifier {
    /**
     * @generated from protobuf enum value: NOTISAREHASHAVE = 0;
     */
    NOTISAREHASHAVE = 0,
    /**
     * @generated from protobuf enum value: ISAREHASHAVE = 1;
     */
    ISAREHASHAVE = 1
}
// @generated message type with reflection information, may provide speed optimized methods
class Argument$Type extends MessageType<Argument> {
    constructor() {
        super("argumentaccess.v1.Argument", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 3, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 4, name: "deleted_at", kind: "message", T: () => Timestamp },
            { no: 5, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "premises", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Premise },
            { no: 7, name: "conditional_statements", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ConditionalStatement },
            { no: 8, name: "conclusion_premise", kind: "message", T: () => Premise }
        ]);
    }
    create(value?: PartialMessage<Argument>): Argument {
        const message = { id: "", title: "", premises: [], conditionalStatements: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Argument>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Argument): Argument {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 2:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 3:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* google.protobuf.Timestamp deleted_at */ 4:
                    message.deletedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.deletedAt);
                    break;
                case /* string title */ 5:
                    message.title = reader.string();
                    break;
                case /* repeated argumentaccess.v1.Premise premises */ 6:
                    message.premises.push(Premise.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated argumentaccess.v1.ConditionalStatement conditional_statements */ 7:
                    message.conditionalStatements.push(ConditionalStatement.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* argumentaccess.v1.Premise conclusion_premise */ 8:
                    message.conclusionPremise = Premise.internalBinaryRead(reader, reader.uint32(), options, message.conclusionPremise);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Argument, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* google.protobuf.Timestamp created_at = 2; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 3; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp deleted_at = 4; */
        if (message.deletedAt)
            Timestamp.internalBinaryWrite(message.deletedAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string title = 5; */
        if (message.title !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.title);
        /* repeated argumentaccess.v1.Premise premises = 6; */
        for (let i = 0; i < message.premises.length; i++)
            Premise.internalBinaryWrite(message.premises[i], writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* repeated argumentaccess.v1.ConditionalStatement conditional_statements = 7; */
        for (let i = 0; i < message.conditionalStatements.length; i++)
            ConditionalStatement.internalBinaryWrite(message.conditionalStatements[i], writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* argumentaccess.v1.Premise conclusion_premise = 8; */
        if (message.conclusionPremise)
            Premise.internalBinaryWrite(message.conclusionPremise, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message argumentaccess.v1.Argument
 */
export const Argument = new Argument$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConditionalStatement$Type extends MessageType<ConditionalStatement> {
    constructor() {
        super("argumentaccess.v1.ConditionalStatement", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 3, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 4, name: "deleted_at", kind: "message", T: () => Timestamp },
            { no: 5, name: "if_premise", kind: "message", T: () => Premise },
            { no: 6, name: "then_premise", kind: "message", T: () => Premise },
            { no: 7, name: "if_proposition", kind: "message", T: () => Proposition },
            { no: 8, name: "then_proposition", kind: "message", T: () => Proposition }
        ]);
    }
    create(value?: PartialMessage<ConditionalStatement>): ConditionalStatement {
        const message = { id: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ConditionalStatement>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConditionalStatement): ConditionalStatement {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 2:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 3:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* google.protobuf.Timestamp deleted_at */ 4:
                    message.deletedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.deletedAt);
                    break;
                case /* argumentaccess.v1.Premise if_premise */ 5:
                    message.ifPremise = Premise.internalBinaryRead(reader, reader.uint32(), options, message.ifPremise);
                    break;
                case /* argumentaccess.v1.Premise then_premise */ 6:
                    message.thenPremise = Premise.internalBinaryRead(reader, reader.uint32(), options, message.thenPremise);
                    break;
                case /* argumentaccess.v1.Proposition if_proposition */ 7:
                    message.ifProposition = Proposition.internalBinaryRead(reader, reader.uint32(), options, message.ifProposition);
                    break;
                case /* argumentaccess.v1.Proposition then_proposition */ 8:
                    message.thenProposition = Proposition.internalBinaryRead(reader, reader.uint32(), options, message.thenProposition);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConditionalStatement, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* google.protobuf.Timestamp created_at = 2; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 3; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp deleted_at = 4; */
        if (message.deletedAt)
            Timestamp.internalBinaryWrite(message.deletedAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* argumentaccess.v1.Premise if_premise = 5; */
        if (message.ifPremise)
            Premise.internalBinaryWrite(message.ifPremise, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* argumentaccess.v1.Premise then_premise = 6; */
        if (message.thenPremise)
            Premise.internalBinaryWrite(message.thenPremise, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* argumentaccess.v1.Proposition if_proposition = 7; */
        if (message.ifProposition)
            Proposition.internalBinaryWrite(message.ifProposition, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* argumentaccess.v1.Proposition then_proposition = 8; */
        if (message.thenProposition)
            Proposition.internalBinaryWrite(message.thenProposition, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message argumentaccess.v1.ConditionalStatement
 */
export const ConditionalStatement = new ConditionalStatement$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Proposition$Type extends MessageType<Proposition> {
    constructor() {
        super("argumentaccess.v1.Proposition", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 3, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 4, name: "deleted_at", kind: "message", T: () => Timestamp },
            { no: 9, name: "proposition_type", kind: "enum", T: () => ["argumentaccess.v1.PropositionType", PropositionType] },
            { no: 10, name: "proposition_sub_premises", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Premise },
            { no: 11, name: "proposition_sub_propositions", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Proposition }
        ]);
    }
    create(value?: PartialMessage<Proposition>): Proposition {
        const message = { id: "", propositionType: 0, propositionSubPremises: [], propositionSubPropositions: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Proposition>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Proposition): Proposition {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 2:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 3:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* google.protobuf.Timestamp deleted_at */ 4:
                    message.deletedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.deletedAt);
                    break;
                case /* argumentaccess.v1.PropositionType proposition_type */ 9:
                    message.propositionType = reader.int32();
                    break;
                case /* repeated argumentaccess.v1.Premise proposition_sub_premises */ 10:
                    message.propositionSubPremises.push(Premise.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated argumentaccess.v1.Proposition proposition_sub_propositions */ 11:
                    message.propositionSubPropositions.push(Proposition.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Proposition, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* google.protobuf.Timestamp created_at = 2; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 3; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp deleted_at = 4; */
        if (message.deletedAt)
            Timestamp.internalBinaryWrite(message.deletedAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* argumentaccess.v1.PropositionType proposition_type = 9; */
        if (message.propositionType !== 0)
            writer.tag(9, WireType.Varint).int32(message.propositionType);
        /* repeated argumentaccess.v1.Premise proposition_sub_premises = 10; */
        for (let i = 0; i < message.propositionSubPremises.length; i++)
            Premise.internalBinaryWrite(message.propositionSubPremises[i], writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* repeated argumentaccess.v1.Proposition proposition_sub_propositions = 11; */
        for (let i = 0; i < message.propositionSubPropositions.length; i++)
            Proposition.internalBinaryWrite(message.propositionSubPropositions[i], writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message argumentaccess.v1.Proposition
 */
export const Proposition = new Proposition$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Premise$Type extends MessageType<Premise> {
    constructor() {
        super("argumentaccess.v1.Premise", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 3, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 4, name: "deleted_at", kind: "message", T: () => Timestamp },
            { no: 5, name: "subject", kind: "message", T: () => Subject },
            { no: 6, name: "subject_quantifier", kind: "enum", T: () => ["argumentaccess.v1.SubjectQuantifier", SubjectQuantifier] },
            { no: 7, name: "predicate", kind: "message", T: () => Predicate },
            { no: 8, name: "predicate_qualifier", kind: "enum", T: () => ["argumentaccess.v1.PredicateQualifier", PredicateQualifier] }
        ]);
    }
    create(value?: PartialMessage<Premise>): Premise {
        const message = { id: "", subjectQuantifier: 0, predicateQualifier: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Premise>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Premise): Premise {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 2:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 3:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* google.protobuf.Timestamp deleted_at */ 4:
                    message.deletedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.deletedAt);
                    break;
                case /* argumentaccess.v1.Subject subject */ 5:
                    message.subject = Subject.internalBinaryRead(reader, reader.uint32(), options, message.subject);
                    break;
                case /* argumentaccess.v1.SubjectQuantifier subject_quantifier */ 6:
                    message.subjectQuantifier = reader.int32();
                    break;
                case /* argumentaccess.v1.Predicate predicate */ 7:
                    message.predicate = Predicate.internalBinaryRead(reader, reader.uint32(), options, message.predicate);
                    break;
                case /* argumentaccess.v1.PredicateQualifier predicate_qualifier */ 8:
                    message.predicateQualifier = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Premise, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* google.protobuf.Timestamp created_at = 2; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 3; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp deleted_at = 4; */
        if (message.deletedAt)
            Timestamp.internalBinaryWrite(message.deletedAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* argumentaccess.v1.Subject subject = 5; */
        if (message.subject)
            Subject.internalBinaryWrite(message.subject, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* argumentaccess.v1.SubjectQuantifier subject_quantifier = 6; */
        if (message.subjectQuantifier !== 0)
            writer.tag(6, WireType.Varint).int32(message.subjectQuantifier);
        /* argumentaccess.v1.Predicate predicate = 7; */
        if (message.predicate)
            Predicate.internalBinaryWrite(message.predicate, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* argumentaccess.v1.PredicateQualifier predicate_qualifier = 8; */
        if (message.predicateQualifier !== 0)
            writer.tag(8, WireType.Varint).int32(message.predicateQualifier);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message argumentaccess.v1.Premise
 */
export const Premise = new Premise$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Subject$Type extends MessageType<Subject> {
    constructor() {
        super("argumentaccess.v1.Subject", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 3, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 4, name: "deleted_at", kind: "message", T: () => Timestamp },
            { no: 5, name: "body", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Subject>): Subject {
        const message = { id: "", body: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Subject>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Subject): Subject {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 2:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 3:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* google.protobuf.Timestamp deleted_at */ 4:
                    message.deletedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.deletedAt);
                    break;
                case /* string body */ 5:
                    message.body = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Subject, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* google.protobuf.Timestamp created_at = 2; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 3; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp deleted_at = 4; */
        if (message.deletedAt)
            Timestamp.internalBinaryWrite(message.deletedAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string body = 5; */
        if (message.body !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.body);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message argumentaccess.v1.Subject
 */
export const Subject = new Subject$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Predicate$Type extends MessageType<Predicate> {
    constructor() {
        super("argumentaccess.v1.Predicate", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 3, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 4, name: "deleted_at", kind: "message", T: () => Timestamp },
            { no: 5, name: "body", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Predicate>): Predicate {
        const message = { id: "", body: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Predicate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Predicate): Predicate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 2:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 3:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* google.protobuf.Timestamp deleted_at */ 4:
                    message.deletedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.deletedAt);
                    break;
                case /* string body */ 5:
                    message.body = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Predicate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* google.protobuf.Timestamp created_at = 2; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 3; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp deleted_at = 4; */
        if (message.deletedAt)
            Timestamp.internalBinaryWrite(message.deletedAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string body = 5; */
        if (message.body !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.body);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message argumentaccess.v1.Predicate
 */
export const Predicate = new Predicate$Type();
