syntax = "proto3";

option go_package = "go/argumentaccess/v1;argumentaccess";

package argumentaccess.v1;

message Argument {
	string id = 1;
	string created_at = 2;
	string updated_at = 3;
	string deleted_at = 4;
	string title = 5;
    repeated Premise premises = 6;
	repeated ConditionalStatement conditional_statements = 7;
	Premise conclusion_premise = 8;
}

enum PropositionType{
    AND = 0;
    OR = 1;
    NAND = 2;
    NOR = 3;
    XOR = 4;
    XNOR = 5;
 }

 enum SubjectQuantifier{
    ALL = 0;
    SOME = 1;
    NONE = 2;
	// PARTICULAR = 3; // TODO do later?
 }

 enum PredicateQualifier{
	NOTISAREHASHAVE = 0;
	ISAREHASHAVE = 1;
 }

message ConditionalStatement {
	string id = 1; // @gotags: bson:"_id"
	string created_at = 2; // @gotags: bson:"created_at"
	string updated_at = 3; // @gotags: bson:"updated_at"
	string deleted_at = 4; // @gotags: bson:"deleted_at"
	Premise if_premise = 5;
	Premise then_premise = 6;
	Proposition if_proposition = 7;
	Proposition then_proposition = 8;
}

message Proposition {
	string id = 1; // @gotags: bson:"_id"
	string created_at = 2; // @gotags: bson:"created_at"
	string updated_at = 3; // @gotags: bson:"updated_at"
	string deleted_at = 4; // @gotags: bson:"deleted_at"
	PropositionType proposition_type = 9;
	repeated Premise proposition_sub_premises = 10;
	repeated Proposition proposition_sub_propositions = 11;
}

message Premise {
	string id = 1; // @gotags: bson:"_id"
	string created_at = 2; // @gotags: bson:"created_at"
	string updated_at = 3; // @gotags: bson:"updated_at"
	string deleted_at = 4; // @gotags: bson:"deleted_at"
    Subject subject = 5; // X is Y, subject = X
    SubjectQuantifier subject_quantifier = 6; // all X is Y, subject_quantifier = all
    Predicate predicate = 7; // X is Y, predicate = Y, premises should have EITHER a subject and a predicate OR subpremises
	PredicateQualifier predicate_qualifier = 8; // AKA is/is not
}

message Subject {
	string id = 1; // @gotags: bson:"_id"
	string created_at = 2; // @gotags: bson:"created_at"
	string updated_at = 3; // @gotags: bson:"updated_at"
	string deleted_at = 4; // @gotags: bson:"deleted_at"
	string body = 5; // @gotags: bson:"body"
}

message Predicate {
	string id = 1; // @gotags: bson:"_id"
	string created_at = 2; // @gotags: bson:"created_at"
	string updated_at = 3; // @gotags: bson:"updated_at"
	string deleted_at = 4; // @gotags: bson:"deleted_at"
	string body = 5; // @gotags: bson:"body"
}