syntax = "proto3";

import "google/protobuf/timestamp.proto";

option go_package = "go/argumentaccess/v1;argumentaccess";

package argumentaccess.v1;

message Argument {
	string id = 1; // @gotags: bson:"_id"
	google.protobuf.Timestamp created_at = 2; // @gotags: bson:"created_at"
	google.protobuf.Timestamp updated_at = 3; // @gotags: bson:"updated_at"
	google.protobuf.Timestamp deleted_at = 4; // @gotags: bson:"deleted_at"
	string title = 5; // @gotags: bson:"title"
    repeated Premise premises = 6; // @gotags: bson:"premises"
	repeated ConditionalStatement conditional_statements = 7; // @gotags: bson:"conditional_statements"
	Premise conclusion_premise = 8; // @gotags: bson:"conclusion_premise"
}

enum PropositionType{
    AND = 0;
    OR = 1;
    NAND = 2;
    NOR = 3;
    XOR = 4;
    XNOR = 5;
 }

 enum SubjectQuantifier{
    ALL = 0;
    SOME = 1;
    NONE = 2;
	// PARTICULAR = 3; // TODO do later?
 }

 enum PredicateQualifier{
	NOTISAREHASHAVE = 0;
	ISAREHASHAVE = 1;
 }

message ConditionalStatement {
	string id = 1; // @gotags: bson:"_id"
	google.protobuf.Timestamp created_at = 2; // @gotags: bson:"created_at"
	google.protobuf.Timestamp updated_at = 3; // @gotags: bson:"updated_at"
	google.protobuf.Timestamp deleted_at = 4; // @gotags: bson:"deleted_at"
	Premise if_premise = 5; // @gotags: bson:"if_premise" 
	Premise then_premise = 6; // @gotags: bson:"then_premise" 
	Proposition if_proposition = 7; // @gotags: bson:"if_proposition" 
	Proposition then_proposition = 8; // @gotags: bson:"then_proposition" 
}

message Proposition {
	string id = 1; // @gotags: bson:"_id"
	google.protobuf.Timestamp created_at = 2; // @gotags: bson:"created_at"
	google.protobuf.Timestamp updated_at = 3; // @gotags: bson:"updated_at"
	google.protobuf.Timestamp deleted_at = 4; // @gotags: bson:"deleted_at"
	PropositionType proposition_type = 9; // @gotags: bson:"proposition_type" 
	repeated Premise proposition_sub_premises = 10; // @gotags: bson:"proposition_sub_premises" 
	repeated Proposition proposition_sub_propositions = 11; // @gotags: bson:"proposition_sub_propositions" 
}

message Premise {
	string id = 1; // @gotags: bson:"_id"
	google.protobuf.Timestamp created_at = 2; // @gotags: bson:"created_at"
	google.protobuf.Timestamp updated_at = 3; // @gotags: bson:"updated_at"
	google.protobuf.Timestamp deleted_at = 4; // @gotags: bson:"deleted_at"
    Subject subject = 5; // @gotags: bson:"subject" 
	// X is Y, subject = X
    SubjectQuantifier subject_quantifier = 6; // @gotags: bson:"subject_quantifier"
	// all X is Y, subject_quantifier = all
    Predicate predicate = 7; // @gotags: bson:"predicate"
	// X is Y, predicate = Y, premises should have EITHER a subject and a predicate OR subpremises
	PredicateQualifier predicate_qualifier = 8; // @gotags: bson:"predicate_qualifier"
	// AKA is/is not
}

message Subject {
	string id = 1; // @gotags: bson:"_id"
	google.protobuf.Timestamp created_at = 2; // @gotags: bson:"created_at"
	google.protobuf.Timestamp updated_at = 3; // @gotags: bson:"updated_at"
	google.protobuf.Timestamp deleted_at = 4; // @gotags: bson:"deleted_at"
	string body = 5; // @gotags: bson:"body"
}

message Predicate {
	string id = 1; // @gotags: bson:"_id"
	google.protobuf.Timestamp created_at = 2; // @gotags: bson:"created_at"
	google.protobuf.Timestamp updated_at = 3; // @gotags: bson:"updated_at"
	google.protobuf.Timestamp deleted_at = 4; // @gotags: bson:"deleted_at"
	string body = 5; // @gotags: bson:"body"
}