syntax = "proto3";

import "google/api/annotations.proto";
import "argumentaccess/v1/argument.proto";

option go_package = "go/argumentaccess/v1;argumentaccess";

package argumentaccess.v1;

service ArgumentAccess {
	rpc Check (HealthCheckRequest) returns (HealthCheckResponse);
	rpc Watch (HealthCheckRequest) returns (stream HealthCheckResponse);

    rpc CreateSubject (CreateSubjectRequest) returns (CreateSubjectResponse) {
		option (google.api.http) = {
			post: "/v1/subject"
			body: '*'
		  };
	} 
    rpc ReadSubject (ReadSubjectRequest) returns (ReadSubjectResponse) {
		option (google.api.http) = {
			get: "/v1/subject"
		  };
	}
    rpc UpdateSubject (UpdateSubjectRequest) returns (UpdateSubjectResponse) {}
    rpc DeleteSubject (DeleteSubjectRequest) returns (DeleteSubjectResponse) {}

	rpc CreatePredicate (CreatePredicateRequest) returns (CreatePredicateResponse) {}
    rpc ReadPredicate (ReadPredicateRequest) returns (ReadPredicateResponse) {}
    rpc UpdatePredicate (UpdatePredicateRequest) returns (UpdatePredicateResponse) {}
    rpc DeletePredicate (DeletePredicateRequest) returns (DeletePredicateResponse) {}

	rpc CreatePremise (CreatePremiseRequest) returns (CreatePremiseResponse) {}
    rpc ReadPremise (ReadPremiseRequest) returns (ReadPremiseResponse) {}
    rpc UpdatePremise (UpdatePremiseRequest) returns (UpdatePremiseResponse) {}
    rpc DeletePremise (DeletePremiseRequest) returns (DeletePremiseResponse) {}

	rpc CreateProposition (CreatePropositionRequest) returns (CreatePropositionResponse) {}
    rpc ReadProposition (ReadPropositionRequest) returns (ReadPropositionResponse) {}
    rpc UpdateProposition (UpdatePropositionRequest) returns (UpdatePropositionResponse) {}
    rpc DeleteProposition (DeletePropositionRequest) returns (DeletePropositionResponse) {}

	rpc CreateConditionalStatement (CreateConditionalStatementRequest) returns (CreateConditionalStatementResponse) {}
    rpc ReadConditionalStatement (ReadConditionalStatementRequest) returns (ReadConditionalStatementResponse) {}
    rpc UpdateConditionalStatement (UpdateConditionalStatementRequest) returns (UpdateConditionalStatementResponse) {}
    rpc DeleteConditionalStatement (DeleteConditionalStatementRequest) returns (DeleteConditionalStatementResponse) {}

	rpc CreateArgument (CreateArgumentRequest) returns (CreateArgumentResponse) {}
    rpc ReadArgument (ReadArgumentRequest) returns (ReadArgumentResponse) {}
    rpc UpdateArgument (UpdateArgumentRequest) returns (UpdateArgumentResponse) {}
    
	
	rpc Test (TestRequest) returns (TestResponse) {
		option (google.api.http) = {
			get: "/test"
		  };
	}
}

message HealthCheckRequest {
	string service = 1;
}

message HealthCheckResponse {
	enum ServingStatus {
	  UNKNOWN = 0;
	  SERVING = 1;
	  NOT_SERVING = 2;
	  SERVICE_UNKNOWN = 3;  // Used only by the Watch method.
	}
	ServingStatus status = 1;
}

message CreateSubjectRequest {
	Subject subject = 1;
}

message CreateSubjectResponse {
	Subject subject = 1;
}

message ReadSubjectRequest {
	optional string subject_id = 1;
}

message ReadSubjectResponse {
	repeated Subject subjects = 1;
}

message UpdateSubjectRequest {
	Subject subject = 1;
}

message UpdateSubjectResponse {
	Subject subject = 1;
}

message DeleteSubjectRequest {
	string subject_id = 1;
}

message DeleteSubjectResponse {
	int64 deleted_count = 1;
}

message CreatePredicateRequest {
	Predicate predicate = 1;
}

message CreatePredicateResponse {
	Predicate predicate = 1;
}

message ReadPredicateRequest {
	string predicate_id = 1;
}

message ReadPredicateResponse {
	repeated Predicate predicates = 1;
}

message UpdatePredicateRequest {
	Predicate predicate = 1;
}

message UpdatePredicateResponse {
	Predicate predicate = 1;
}

message DeletePredicateRequest {
	string predicate_id = 1;
}

message DeletePredicateResponse {
	int64 deleted_count = 1;
}

message CreatePremiseRequest {
	Premise premise = 1;
}

message CreatePremiseResponse {
	Premise premise = 1;
}

message ReadPremiseRequest {
	string premise_id = 1;
}

message ReadPremiseResponse {
	repeated Premise premises = 1;
}

message UpdatePremiseRequest {
	Premise premise = 1;
}

message UpdatePremiseResponse {
	Premise premise = 1;
}

message DeletePremiseRequest {
	string premise_id = 1;
}

message DeletePremiseResponse {
	int64 deleted_count = 1;
}

message CreatePropositionRequest {
	Proposition proposition = 1;
}

message CreatePropositionResponse {
	Proposition proposition = 1;
}

message ReadPropositionRequest {
	string proposition_id = 1;
}

message ReadPropositionResponse {
	repeated Proposition propositions = 1;
}

message UpdatePropositionRequest {
	Proposition proposition = 1;
}

message UpdatePropositionResponse {
	Proposition proposition = 1;
}

message DeletePropositionRequest {
	string proposition_id = 1;
}

message DeletePropositionResponse {
	int64 deleted_count = 1;
}

message CreateConditionalStatementRequest {
	ConditionalStatement conditional_statement = 1;
}

message CreateConditionalStatementResponse {
	ConditionalStatement conditional_statement = 1;
}

message ReadConditionalStatementRequest {
	string conditional_statement_id = 1;
}

message ReadConditionalStatementResponse {
	repeated ConditionalStatement conditional_statements = 1;
}

message UpdateConditionalStatementRequest {
	ConditionalStatement conditional_statement = 1;
}

message UpdateConditionalStatementResponse {
	ConditionalStatement conditional_statement = 1;
}

message DeleteConditionalStatementRequest {
	string conditional_statement_id = 1;
}

message DeleteConditionalStatementResponse {
	int64 deleted_count = 1;
}

message CreateArgumentRequest {
	Argument argument = 1;
}

message CreateArgumentResponse {
	Argument argument = 1;
}

message ReadArgumentRequest {
	string argument_id = 1;
}

message ReadArgumentResponse {
	repeated Argument arguments = 1;
}

message UpdateArgumentRequest {
	Argument argument = 1;
}

message UpdateArgumentResponse {
	Argument argument = 1;
}

message DeleteArgumentRequest {
	string argument_id = 1;
}

message DeleteArgumentResponse {
	int64 deleted_count = 1;
}

message TestRequest {
}

message TestResponse {
}