// @generated by protobuf-ts 2.8.2 with parameter generate_dependencies
// @generated from protobuf file "argumentaccess/v1/server.proto" (package "argumentaccess.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ArgumentAccess } from "./server";
import type { DeleteArgumentResponse } from "./server";
import type { DeleteArgumentRequest } from "./server";
import type { UpdateArgumentResponse } from "./server";
import type { UpdateArgumentRequest } from "./server";
import type { ReadArgumentResponse } from "./server";
import type { ReadArgumentRequest } from "./server";
import type { CreateArgumentResponse } from "./server";
import type { CreateArgumentRequest } from "./server";
import type { DeleteConditionalStatementResponse } from "./server";
import type { DeleteConditionalStatementRequest } from "./server";
import type { UpdateConditionalStatementResponse } from "./server";
import type { UpdateConditionalStatementRequest } from "./server";
import type { ReadConditionalStatementResponse } from "./server";
import type { ReadConditionalStatementRequest } from "./server";
import type { CreateConditionalStatementResponse } from "./server";
import type { CreateConditionalStatementRequest } from "./server";
import type { DeletePropositionResponse } from "./server";
import type { DeletePropositionRequest } from "./server";
import type { UpdatePropositionResponse } from "./server";
import type { UpdatePropositionRequest } from "./server";
import type { ReadPropositionResponse } from "./server";
import type { ReadPropositionRequest } from "./server";
import type { CreatePropositionResponse } from "./server";
import type { CreatePropositionRequest } from "./server";
import type { DeletePremiseResponse } from "./server";
import type { DeletePremiseRequest } from "./server";
import type { UpdatePremiseResponse } from "./server";
import type { UpdatePremiseRequest } from "./server";
import type { ReadPremiseResponse } from "./server";
import type { ReadPremiseRequest } from "./server";
import type { CreatePremiseResponse } from "./server";
import type { CreatePremiseRequest } from "./server";
import type { DeletePredicateResponse } from "./server";
import type { DeletePredicateRequest } from "./server";
import type { UpdatePredicateResponse } from "./server";
import type { UpdatePredicateRequest } from "./server";
import type { ReadPredicateResponse } from "./server";
import type { ReadPredicateRequest } from "./server";
import type { CreatePredicateResponse } from "./server";
import type { CreatePredicateRequest } from "./server";
import type { DeleteSubjectResponse } from "./server";
import type { DeleteSubjectRequest } from "./server";
import type { UpdateSubjectResponse } from "./server";
import type { UpdateSubjectRequest } from "./server";
import type { ReadSubjectResponse } from "./server";
import type { ReadSubjectRequest } from "./server";
import type { CreateSubjectResponse } from "./server";
import type { CreateSubjectRequest } from "./server";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { HealthCheckResponse } from "./server";
import type { HealthCheckRequest } from "./server";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service argumentaccess.v1.ArgumentAccess
 */
export interface IArgumentAccessClient {
    /**
     * @generated from protobuf rpc: Check(argumentaccess.v1.HealthCheckRequest) returns (argumentaccess.v1.HealthCheckResponse);
     */
    check(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckResponse>;
    /**
     * @generated from protobuf rpc: Watch(argumentaccess.v1.HealthCheckRequest) returns (stream argumentaccess.v1.HealthCheckResponse);
     */
    watch(input: HealthCheckRequest, options?: RpcOptions): ServerStreamingCall<HealthCheckRequest, HealthCheckResponse>;
    /**
     * @generated from protobuf rpc: CreateSubject(argumentaccess.v1.CreateSubjectRequest) returns (argumentaccess.v1.CreateSubjectResponse);
     */
    createSubject(input: CreateSubjectRequest, options?: RpcOptions): UnaryCall<CreateSubjectRequest, CreateSubjectResponse>;
    /**
     * @generated from protobuf rpc: ReadSubject(argumentaccess.v1.ReadSubjectRequest) returns (argumentaccess.v1.ReadSubjectResponse);
     */
    readSubject(input: ReadSubjectRequest, options?: RpcOptions): UnaryCall<ReadSubjectRequest, ReadSubjectResponse>;
    /**
     * @generated from protobuf rpc: UpdateSubject(argumentaccess.v1.UpdateSubjectRequest) returns (argumentaccess.v1.UpdateSubjectResponse);
     */
    updateSubject(input: UpdateSubjectRequest, options?: RpcOptions): UnaryCall<UpdateSubjectRequest, UpdateSubjectResponse>;
    /**
     * @generated from protobuf rpc: DeleteSubject(argumentaccess.v1.DeleteSubjectRequest) returns (argumentaccess.v1.DeleteSubjectResponse);
     */
    deleteSubject(input: DeleteSubjectRequest, options?: RpcOptions): UnaryCall<DeleteSubjectRequest, DeleteSubjectResponse>;
    /**
     * @generated from protobuf rpc: CreatePredicate(argumentaccess.v1.CreatePredicateRequest) returns (argumentaccess.v1.CreatePredicateResponse);
     */
    createPredicate(input: CreatePredicateRequest, options?: RpcOptions): UnaryCall<CreatePredicateRequest, CreatePredicateResponse>;
    /**
     * @generated from protobuf rpc: ReadPredicate(argumentaccess.v1.ReadPredicateRequest) returns (argumentaccess.v1.ReadPredicateResponse);
     */
    readPredicate(input: ReadPredicateRequest, options?: RpcOptions): UnaryCall<ReadPredicateRequest, ReadPredicateResponse>;
    /**
     * @generated from protobuf rpc: UpdatePredicate(argumentaccess.v1.UpdatePredicateRequest) returns (argumentaccess.v1.UpdatePredicateResponse);
     */
    updatePredicate(input: UpdatePredicateRequest, options?: RpcOptions): UnaryCall<UpdatePredicateRequest, UpdatePredicateResponse>;
    /**
     * @generated from protobuf rpc: DeletePredicate(argumentaccess.v1.DeletePredicateRequest) returns (argumentaccess.v1.DeletePredicateResponse);
     */
    deletePredicate(input: DeletePredicateRequest, options?: RpcOptions): UnaryCall<DeletePredicateRequest, DeletePredicateResponse>;
    /**
     * @generated from protobuf rpc: CreatePremise(argumentaccess.v1.CreatePremiseRequest) returns (argumentaccess.v1.CreatePremiseResponse);
     */
    createPremise(input: CreatePremiseRequest, options?: RpcOptions): UnaryCall<CreatePremiseRequest, CreatePremiseResponse>;
    /**
     * @generated from protobuf rpc: ReadPremise(argumentaccess.v1.ReadPremiseRequest) returns (argumentaccess.v1.ReadPremiseResponse);
     */
    readPremise(input: ReadPremiseRequest, options?: RpcOptions): UnaryCall<ReadPremiseRequest, ReadPremiseResponse>;
    /**
     * @generated from protobuf rpc: UpdatePremise(argumentaccess.v1.UpdatePremiseRequest) returns (argumentaccess.v1.UpdatePremiseResponse);
     */
    updatePremise(input: UpdatePremiseRequest, options?: RpcOptions): UnaryCall<UpdatePremiseRequest, UpdatePremiseResponse>;
    /**
     * @generated from protobuf rpc: DeletePremise(argumentaccess.v1.DeletePremiseRequest) returns (argumentaccess.v1.DeletePremiseResponse);
     */
    deletePremise(input: DeletePremiseRequest, options?: RpcOptions): UnaryCall<DeletePremiseRequest, DeletePremiseResponse>;
    /**
     * @generated from protobuf rpc: CreateProposition(argumentaccess.v1.CreatePropositionRequest) returns (argumentaccess.v1.CreatePropositionResponse);
     */
    createProposition(input: CreatePropositionRequest, options?: RpcOptions): UnaryCall<CreatePropositionRequest, CreatePropositionResponse>;
    /**
     * @generated from protobuf rpc: ReadProposition(argumentaccess.v1.ReadPropositionRequest) returns (argumentaccess.v1.ReadPropositionResponse);
     */
    readProposition(input: ReadPropositionRequest, options?: RpcOptions): UnaryCall<ReadPropositionRequest, ReadPropositionResponse>;
    /**
     * @generated from protobuf rpc: UpdateProposition(argumentaccess.v1.UpdatePropositionRequest) returns (argumentaccess.v1.UpdatePropositionResponse);
     */
    updateProposition(input: UpdatePropositionRequest, options?: RpcOptions): UnaryCall<UpdatePropositionRequest, UpdatePropositionResponse>;
    /**
     * @generated from protobuf rpc: DeleteProposition(argumentaccess.v1.DeletePropositionRequest) returns (argumentaccess.v1.DeletePropositionResponse);
     */
    deleteProposition(input: DeletePropositionRequest, options?: RpcOptions): UnaryCall<DeletePropositionRequest, DeletePropositionResponse>;
    /**
     * @generated from protobuf rpc: CreateConditionalStatement(argumentaccess.v1.CreateConditionalStatementRequest) returns (argumentaccess.v1.CreateConditionalStatementResponse);
     */
    createConditionalStatement(input: CreateConditionalStatementRequest, options?: RpcOptions): UnaryCall<CreateConditionalStatementRequest, CreateConditionalStatementResponse>;
    /**
     * @generated from protobuf rpc: ReadConditionalStatement(argumentaccess.v1.ReadConditionalStatementRequest) returns (argumentaccess.v1.ReadConditionalStatementResponse);
     */
    readConditionalStatement(input: ReadConditionalStatementRequest, options?: RpcOptions): UnaryCall<ReadConditionalStatementRequest, ReadConditionalStatementResponse>;
    /**
     * @generated from protobuf rpc: UpdateConditionalStatement(argumentaccess.v1.UpdateConditionalStatementRequest) returns (argumentaccess.v1.UpdateConditionalStatementResponse);
     */
    updateConditionalStatement(input: UpdateConditionalStatementRequest, options?: RpcOptions): UnaryCall<UpdateConditionalStatementRequest, UpdateConditionalStatementResponse>;
    /**
     * @generated from protobuf rpc: DeleteConditionalStatement(argumentaccess.v1.DeleteConditionalStatementRequest) returns (argumentaccess.v1.DeleteConditionalStatementResponse);
     */
    deleteConditionalStatement(input: DeleteConditionalStatementRequest, options?: RpcOptions): UnaryCall<DeleteConditionalStatementRequest, DeleteConditionalStatementResponse>;
    /**
     * @generated from protobuf rpc: CreateArgument(argumentaccess.v1.CreateArgumentRequest) returns (argumentaccess.v1.CreateArgumentResponse);
     */
    createArgument(input: CreateArgumentRequest, options?: RpcOptions): UnaryCall<CreateArgumentRequest, CreateArgumentResponse>;
    /**
     * @generated from protobuf rpc: ReadArgument(argumentaccess.v1.ReadArgumentRequest) returns (argumentaccess.v1.ReadArgumentResponse);
     */
    readArgument(input: ReadArgumentRequest, options?: RpcOptions): UnaryCall<ReadArgumentRequest, ReadArgumentResponse>;
    /**
     * @generated from protobuf rpc: UpdateArgument(argumentaccess.v1.UpdateArgumentRequest) returns (argumentaccess.v1.UpdateArgumentResponse);
     */
    updateArgument(input: UpdateArgumentRequest, options?: RpcOptions): UnaryCall<UpdateArgumentRequest, UpdateArgumentResponse>;
    /**
     * @generated from protobuf rpc: DeleteArgument(argumentaccess.v1.DeleteArgumentRequest) returns (argumentaccess.v1.DeleteArgumentResponse);
     */
    deleteArgument(input: DeleteArgumentRequest, options?: RpcOptions): UnaryCall<DeleteArgumentRequest, DeleteArgumentResponse>;
}
/**
 * @generated from protobuf service argumentaccess.v1.ArgumentAccess
 */
export class ArgumentAccessClient implements IArgumentAccessClient, ServiceInfo {
    typeName = ArgumentAccess.typeName;
    methods = ArgumentAccess.methods;
    options = ArgumentAccess.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Check(argumentaccess.v1.HealthCheckRequest) returns (argumentaccess.v1.HealthCheckResponse);
     */
    check(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HealthCheckRequest, HealthCheckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Watch(argumentaccess.v1.HealthCheckRequest) returns (stream argumentaccess.v1.HealthCheckResponse);
     */
    watch(input: HealthCheckRequest, options?: RpcOptions): ServerStreamingCall<HealthCheckRequest, HealthCheckResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<HealthCheckRequest, HealthCheckResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateSubject(argumentaccess.v1.CreateSubjectRequest) returns (argumentaccess.v1.CreateSubjectResponse);
     */
    createSubject(input: CreateSubjectRequest, options?: RpcOptions): UnaryCall<CreateSubjectRequest, CreateSubjectResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateSubjectRequest, CreateSubjectResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadSubject(argumentaccess.v1.ReadSubjectRequest) returns (argumentaccess.v1.ReadSubjectResponse);
     */
    readSubject(input: ReadSubjectRequest, options?: RpcOptions): UnaryCall<ReadSubjectRequest, ReadSubjectResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadSubjectRequest, ReadSubjectResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateSubject(argumentaccess.v1.UpdateSubjectRequest) returns (argumentaccess.v1.UpdateSubjectResponse);
     */
    updateSubject(input: UpdateSubjectRequest, options?: RpcOptions): UnaryCall<UpdateSubjectRequest, UpdateSubjectResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateSubjectRequest, UpdateSubjectResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteSubject(argumentaccess.v1.DeleteSubjectRequest) returns (argumentaccess.v1.DeleteSubjectResponse);
     */
    deleteSubject(input: DeleteSubjectRequest, options?: RpcOptions): UnaryCall<DeleteSubjectRequest, DeleteSubjectResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteSubjectRequest, DeleteSubjectResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreatePredicate(argumentaccess.v1.CreatePredicateRequest) returns (argumentaccess.v1.CreatePredicateResponse);
     */
    createPredicate(input: CreatePredicateRequest, options?: RpcOptions): UnaryCall<CreatePredicateRequest, CreatePredicateResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePredicateRequest, CreatePredicateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadPredicate(argumentaccess.v1.ReadPredicateRequest) returns (argumentaccess.v1.ReadPredicateResponse);
     */
    readPredicate(input: ReadPredicateRequest, options?: RpcOptions): UnaryCall<ReadPredicateRequest, ReadPredicateResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadPredicateRequest, ReadPredicateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePredicate(argumentaccess.v1.UpdatePredicateRequest) returns (argumentaccess.v1.UpdatePredicateResponse);
     */
    updatePredicate(input: UpdatePredicateRequest, options?: RpcOptions): UnaryCall<UpdatePredicateRequest, UpdatePredicateResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePredicateRequest, UpdatePredicateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePredicate(argumentaccess.v1.DeletePredicateRequest) returns (argumentaccess.v1.DeletePredicateResponse);
     */
    deletePredicate(input: DeletePredicateRequest, options?: RpcOptions): UnaryCall<DeletePredicateRequest, DeletePredicateResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePredicateRequest, DeletePredicateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreatePremise(argumentaccess.v1.CreatePremiseRequest) returns (argumentaccess.v1.CreatePremiseResponse);
     */
    createPremise(input: CreatePremiseRequest, options?: RpcOptions): UnaryCall<CreatePremiseRequest, CreatePremiseResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePremiseRequest, CreatePremiseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadPremise(argumentaccess.v1.ReadPremiseRequest) returns (argumentaccess.v1.ReadPremiseResponse);
     */
    readPremise(input: ReadPremiseRequest, options?: RpcOptions): UnaryCall<ReadPremiseRequest, ReadPremiseResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadPremiseRequest, ReadPremiseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePremise(argumentaccess.v1.UpdatePremiseRequest) returns (argumentaccess.v1.UpdatePremiseResponse);
     */
    updatePremise(input: UpdatePremiseRequest, options?: RpcOptions): UnaryCall<UpdatePremiseRequest, UpdatePremiseResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePremiseRequest, UpdatePremiseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePremise(argumentaccess.v1.DeletePremiseRequest) returns (argumentaccess.v1.DeletePremiseResponse);
     */
    deletePremise(input: DeletePremiseRequest, options?: RpcOptions): UnaryCall<DeletePremiseRequest, DeletePremiseResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePremiseRequest, DeletePremiseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateProposition(argumentaccess.v1.CreatePropositionRequest) returns (argumentaccess.v1.CreatePropositionResponse);
     */
    createProposition(input: CreatePropositionRequest, options?: RpcOptions): UnaryCall<CreatePropositionRequest, CreatePropositionResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePropositionRequest, CreatePropositionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadProposition(argumentaccess.v1.ReadPropositionRequest) returns (argumentaccess.v1.ReadPropositionResponse);
     */
    readProposition(input: ReadPropositionRequest, options?: RpcOptions): UnaryCall<ReadPropositionRequest, ReadPropositionResponse> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadPropositionRequest, ReadPropositionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateProposition(argumentaccess.v1.UpdatePropositionRequest) returns (argumentaccess.v1.UpdatePropositionResponse);
     */
    updateProposition(input: UpdatePropositionRequest, options?: RpcOptions): UnaryCall<UpdatePropositionRequest, UpdatePropositionResponse> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePropositionRequest, UpdatePropositionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteProposition(argumentaccess.v1.DeletePropositionRequest) returns (argumentaccess.v1.DeletePropositionResponse);
     */
    deleteProposition(input: DeletePropositionRequest, options?: RpcOptions): UnaryCall<DeletePropositionRequest, DeletePropositionResponse> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeletePropositionRequest, DeletePropositionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateConditionalStatement(argumentaccess.v1.CreateConditionalStatementRequest) returns (argumentaccess.v1.CreateConditionalStatementResponse);
     */
    createConditionalStatement(input: CreateConditionalStatementRequest, options?: RpcOptions): UnaryCall<CreateConditionalStatementRequest, CreateConditionalStatementResponse> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateConditionalStatementRequest, CreateConditionalStatementResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadConditionalStatement(argumentaccess.v1.ReadConditionalStatementRequest) returns (argumentaccess.v1.ReadConditionalStatementResponse);
     */
    readConditionalStatement(input: ReadConditionalStatementRequest, options?: RpcOptions): UnaryCall<ReadConditionalStatementRequest, ReadConditionalStatementResponse> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadConditionalStatementRequest, ReadConditionalStatementResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateConditionalStatement(argumentaccess.v1.UpdateConditionalStatementRequest) returns (argumentaccess.v1.UpdateConditionalStatementResponse);
     */
    updateConditionalStatement(input: UpdateConditionalStatementRequest, options?: RpcOptions): UnaryCall<UpdateConditionalStatementRequest, UpdateConditionalStatementResponse> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateConditionalStatementRequest, UpdateConditionalStatementResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteConditionalStatement(argumentaccess.v1.DeleteConditionalStatementRequest) returns (argumentaccess.v1.DeleteConditionalStatementResponse);
     */
    deleteConditionalStatement(input: DeleteConditionalStatementRequest, options?: RpcOptions): UnaryCall<DeleteConditionalStatementRequest, DeleteConditionalStatementResponse> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteConditionalStatementRequest, DeleteConditionalStatementResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateArgument(argumentaccess.v1.CreateArgumentRequest) returns (argumentaccess.v1.CreateArgumentResponse);
     */
    createArgument(input: CreateArgumentRequest, options?: RpcOptions): UnaryCall<CreateArgumentRequest, CreateArgumentResponse> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateArgumentRequest, CreateArgumentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadArgument(argumentaccess.v1.ReadArgumentRequest) returns (argumentaccess.v1.ReadArgumentResponse);
     */
    readArgument(input: ReadArgumentRequest, options?: RpcOptions): UnaryCall<ReadArgumentRequest, ReadArgumentResponse> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadArgumentRequest, ReadArgumentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateArgument(argumentaccess.v1.UpdateArgumentRequest) returns (argumentaccess.v1.UpdateArgumentResponse);
     */
    updateArgument(input: UpdateArgumentRequest, options?: RpcOptions): UnaryCall<UpdateArgumentRequest, UpdateArgumentResponse> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateArgumentRequest, UpdateArgumentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteArgument(argumentaccess.v1.DeleteArgumentRequest) returns (argumentaccess.v1.DeleteArgumentResponse);
     */
    deleteArgument(input: DeleteArgumentRequest, options?: RpcOptions): UnaryCall<DeleteArgumentRequest, DeleteArgumentResponse> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteArgumentRequest, DeleteArgumentResponse>("unary", this._transport, method, opt, input);
    }
}
